"""Gate matrices and the tracker-facing unitary application."""

import numpy as np

from qetwork.operations.core import _apply_unitary
from qetwork.operations.err_channels import dephase, depolarize

_ISQRT2 = 1 / np.sqrt(2)

# --- single qubit ---
I = np.array([[1, 0], [0, 1]], dtype=complex)
X = np.array([[0, 1], [1, 0]], dtype=complex)
Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)
H = _ISQRT2 * np.array([[1, 1], [1, -1]], dtype=complex)
S = np.array([[1, 0], [0, 1j]], dtype=complex)

# --- two qubit ---
# CONVENTION: keys[0] is the CONTROL, keys[1] is the TARGET.
# _embed places the operator's factors at `indices` in the order given, so the
# order you pass keys in *is* the control/target assignment. Reversing them
# yields a valid-looking simulation with silently wrong results.
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]], dtype=complex)
CZ   = np.diag([1, 1, 1, -1]).astype(complex)
SWAP = np.array([[1, 0, 0, 0],
                 [0, 0, 1, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1]], dtype=complex)

def rx(theta: float) -> np.ndarray:
    c, s = np.cos(theta / 2), np.sin(theta / 2)
    return np.array([[c, -1j * s], [-1j * s, c]], dtype=complex)


def ry(theta: float) -> np.ndarray:
    c, s = np.cos(theta / 2), np.sin(theta / 2)
    return np.array([[c, -s], [s, c]], dtype=complex)


def rz(theta: float) -> np.ndarray:
    e = np.exp(1j * theta / 2)
    return np.array([[e.conjugate(), 0], [0, e]], dtype=complex)


def phase(phi: float) -> np.ndarray:
    return np.array([[1, 0], [0, np.exp(1j * phi)]], dtype=complex)


def apply_unitary(tracker, keys: tuple[int, ...], U: np.ndarray) -> None:
    """READ (merge if needed) -> COMPUTE -> WRITE. The only mutation is set()."""
    keys = tuple(keys)
    if not keys:
        raise ValueError("applying a unitary requires at least one key")
    if len(set(keys)) != len(keys):
        raise ValueError(f"keys must be unique, got {keys}")
    k = len(keys)
    if U.shape != (2**k, 2**k):
        raise ValueError(f"U must be 2^{k} x 2^{k} for {k} target qubits, got {U.shape}")
    if not np.allclose(U.conj().T @ U, np.eye(2**k)):
        raise ValueError("U must be unitary: U^dag @ U deviates from I")
    joint = tracker.combine(keys)
    indices = tuple(joint.index(key) for key in keys)
    tracker.set(joint, _apply_unitary(tracker.get(keys[0]).matrix, U, indices))

def apply_gate(tracker, keys: tuple[int, ...], U: np.ndarray,
               p_depol: float = 0.0, coherent: np.ndarray | None = None) -> None:
    """Ideal unitary + gate error. Noise FOLLOWS the gate, matching the RB convention.

    `coherent` is a systematic miscalibration (over-rotation, residual Rz) applied
    after the ideal U; `p_depol` is the incoherent remainder as a joint k-qubit
    depolarizing channel. Duration/decoherence is the CALLER's job — see Node.
    """
    # CITE gate-noise-order | randomized benchmarking measures error as a channel composed AFTER the ideal Clifford; modelling it as U-then-noise is what makes p recoverable from a measured EPG | Magesan, Gambetta, Emerson, "Scalable and robust randomized benchmarking of quantum processes", PRL 106, 180504 (2011)
    keys = tuple(keys)
    k = len(keys)
    if not 0 <= p_depol <= 1:
        raise ValueError(f"p_depol must be in [0,1], got {p_depol}")
    if coherent is not None:
        if coherent.shape != (2**k, 2**k):
            raise ValueError(f"coherent must be 2^{k} x 2^{k}, got {coherent.shape}")
        if not np.allclose(coherent.conj().T @ coherent, np.eye(2**k)):
            raise ValueError("coherent must be unitary: coherent^dag @ coherent deviates from I")
        U = coherent @ U
    apply_unitary(tracker, keys, U)
    depolarize(tracker, keys, p_depol)

# --- single-qubit Clifford group (network benchmarking) ---

def _clifford_canonical(U: np.ndarray, tol: int = 6) -> tuple:
    """Hashable form of U modulo global phase (divide out the first nonzero entry's phase)."""
    for x in U.reshape(-1):
        if abs(x) > 1e-9:
            U = U * (abs(x) / x)
            break
    return tuple(np.round(U.reshape(-1), tol))


def _clifford_group_1q() -> list[np.ndarray]:
    """The 24 single-qubit Cliffords (mod global phase), generated by closure from {H, S}.

    Generating the group beats hand-listing gate sequences: a hand list can silently hold a
    duplicate (two sequences equal up to phase), dropping an element and breaking the
    2-design property RB depends on.
    """
    elems = {_clifford_canonical(I): I}
    frontier = [I]
    while frontier:
        nxt = []
        for U in frontier:
            for g in (H, S):
                V = g @ U
                k = _clifford_canonical(V)
                if k not in elems:
                    elems[k] = V
                    nxt.append(V)
        frontier = nxt
    return list(elems.values())


CLIFFORD_1Q: list[np.ndarray] = _clifford_group_1q()   # exactly 24


def random_clifford(rng) -> np.ndarray:
    """A uniformly random single-qubit Clifford unitary."""
    return CLIFFORD_1Q[int(rng.integers(0, len(CLIFFORD_1Q)))]
